<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>An opinionated C# Toolkit targeting Amazon Bedrock for Microsoft Agent Framework that makes life eaisier</Description>
	</PropertyGroup>

	<Import Project="..\..\nuget-package.props" />

	<ItemGroup>
		<PackageReference Include="AWS.Bedrock.MEAI" />
		<PackageReference Include="Microsoft.Agents.AI" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AgentFrameworkToolkit\AgentFrameworkToolkit.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
